version: 2
services:
  - name: mongo
    type: docker
    buildCommand: docker build -t mongo ./mongo-custom
    startCommand: docker run --name pawq-mongo -p 27017:27017 --env-file .env mongo
    volumes:
      - name: initial-data
        path: /docker-entrypoint-initdb.d/initial_data_script.py
        readOnly: true
    env:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - port: 27017
        protocol: tcp
volumes:
  - name: initial-data
