version: 2
services:
  - type: pserv
    name: mongodb
    runtime: docker
    buildCommand: docker build -t mongo ./mongo-custom
    startCommand: docker run --name pawq-mongo -p 27017:27017 --env-file .env mongo
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        fromEnv: MONGO_INITDB_ROOT_USERNAME
      - key: MONGO_INITDB_ROOT_PASSWORD
        fromEnv: MONGO_INITDB_ROOT_PASSWORD
      - key: MONGO_INITDB_DATABASE
        fromEnv: MONGO_INITDB_DATABASE
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
